gfp:
  label: avGFP
  
  phenotypes:
    brightness: ["phenotype"]
  
  lantern:
    prediction:
      cuda: True
  
  feedforward:
    prediction:
      cuda: True
  
  alphabet: ["A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y","*"]

laci:
  label: LacI
  
  phenotypes:
    joint: ["ec50-norm", "ginf-norm"]
    ec50: ["ec50-norm"]
    ginf: ["ginf-norm"]
  
  errors:
    joint: ["ec50-norm-var", "dummy-var"]
    ec50: ["ec50-norm-var"]
  
  lantern:
    prediction:
      cuda: True
  
  feedforward:
    prediction:
      cuda: True

covid:
  label: SARS-CoV-2
  substitutions: aa_substitutions
  
  phenotypes:
    joint: ["func_score_norm_exp", "func_score_norm_bind"]
    exp: ["func_score_norm_exp"]
    bind: ["func_score_norm_bind"]
  
  errors:
    joint: ["func_score_var_norm_exp", "func_score_var_norm_bind"]
    exp: ["func_score_var_norm_exp"]
    bind: ["func_score_var_norm_bind"]
  
  lantern:
    prediction:
      cuda: True
  
  feedforward:
    prediction:
      cuda: True
