gfp:
  label: avGFP
  
  phenotypes:
    brightness:
      col: "phenotype"
  
  lantern:
    prediction:
      cuda: False
  
  feedforward:
    prediction:
      cuda: False
  
  alphabet: ["A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y","*"]
