gfp:
  label: avGFP
  N: 45000
  
  phenotypes:
    brightness: ["phenotype"]
  
  lantern:
    prediction:
      cuda: True
  
  feedforward:
    prediction:
      cuda: True
  
  alphabet: ["A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y","*"]

laci:
  label: LacI
  N: 40000
  
  phenotypes:
    joint: ["ec50-norm", "ginf-norm"]
    ec50: ["ec50-norm"]
    ginf: ["ginf-norm"]
  
  errors:
    joint: ["ec50-norm-var", "dummy-var"]
    ec50: ["ec50-norm-var"]
  
  lantern:
    prediction:
      cuda: True
  
  feedforward:
    prediction:
      cuda: True

covid:
  N: 125000
  label: SARS-CoV-2
  substitutions: aa_substitutions
  
  phenotypes:
    joint: ["func_score_norm_exp", "func_score_norm_bind"]
    exp: ["func_score_norm_exp"]
    bind: ["func_score_norm_bind"]
  
  errors:
    joint: ["func_score_var_norm_exp", "func_score_var_norm_bind"]
    exp: ["func_score_var_norm_exp"]
    bind: ["func_score_var_norm_bind"]
  
  lantern:
    prediction:
      cuda: True
  
  feedforward:
    prediction:
      cuda: True

figures:
  surface:
    gfp-brightness:
      brightness:
        raw: "medianBrightness"
        cbar_title: "avGFP\nBrightness"
        cbar_kwargs:
          aspect: 8
          shrink: 0.8

    laci-joint:
      ec50:
        raw: "ec50"
        log: True
        fig_kwargs:
          figsize: [5, 3]
        cbar_title: "LacI\n$\\mathrm{EC}_{50}$"
        cbar_kwargs:
          aspect: 8
          shrink: 0.6
        plot_kwargs:
          log_tick_subs: [0.333, 0.666, 1.0]
          levels: 10

      ginf:
        raw: "ginf"
        log: True
        p: 1
        cbar_title: "LacI\n$\\mathrm{G}_{\\infty}$"
        fig_kwargs:
          figsize: [5, 3]
        cbar_kwargs:
          aspect: 8
          shrink: 0.6
        plot_kwargs:
          log_tick_subs: [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0]
          levels: 10


    covid-joint:
      exp:
        raw: "func_score_exp"
        cbar_title: "RBD\n$\\Delta \\log$MFI"
        cbar_kwargs:
          aspect: 8
          shrink: 0.8

      bind:
        raw: "func_score_bind"
        p: 1
        cbar_title: "RBD-ACE2\n$\\log_{10} K_d$"
        cbar_kwargs:
          aspect: 8
          shrink: 0.8

  diffops:
    gfp-brightness:
      brightness:
        dims: 3

    laci-joint:
      ec50:
        dims: 3
        zlim: [-2.1, 3.4, -0.6, 0.6]
        midpoint: 0.1
        plot_kwargs:
          log_tick_subs: [0.333, 0.666, 1.0]
          levels: 12

      ginf:
        dims: 3

    covid-joint:
      exp:
        dims: 5

      bind:
        dims: 5
        zlim: [-3.5, 3, -3.1, 3.8]
        N: 25
        cbar_kwargs:
          pad: 0.1
        cbar_title: "SARS-CoV-2\nRBD-ACE2\n$\\log_{10} K_d$"
